version: 2
updates:
  - package-ecosystem: "terraform"
    directories:
      - "/"
      - "/examples/basic"
      - "/examples/advanced"
      - "/wrappers"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tehran"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "terraform"
    open-pull-requests-limit: 5
